# EE2211 Tutorial 6 

### by Chua Dingjuan (Sept 2022)

## Question 2 - Note : official solutions do not provide python codes, below are suggested possible python codes. 

#### 2(a) Perform a 3rd-order polynomial regression and sketch the result of line fitting.

#### 2(b) Given a test point { x = 9 } predict y using the polynomial model.


## Possible Python Solutions as below

In [1]:
import numpy as np
import matplotlib.pyplot as plt

### Q2(a) - SOLUTION v1 - Solving Using scikit (sklearn) PolynomialFeatures function


In [2]:
# These two lines of code are jupyter specific and install sklearn.

# If you already have sklearn (scikit), You do not need to include these codes for running your codes.

import sys
!{sys.executable} -m pip install -q sklearn 

In [8]:
### Q2(a) - SOLUTION v1 - Solving Using scikit (sklearn) PolynomialFeatures function

#Creating two column arrays for x and y
x = np.array([[-10, -8, -3, -1,  2,  8]]).T
y = np.array([[5, 5, 4, 3, 2, 2]]).T

# We will generate polynomial matrix P using the following function from sklearn.preprocessing.PolynomialFeatures
# Name of function is PolynomialFeatures
# shortcut name skpf
from sklearn.preprocessing import PolynomialFeatures as skpf

#step 1, create a polynomial function object class with the right degree
polyfn = skpf(3)
print(type(polyfn))

#step 2, fit the polyfn to your actual data
#fit_transform will create the P matrix (polynomial coefficients) accordingly
P=polyfn.fit_transform(x)

print('\nP is \n', P) 


<class 'sklearn.preprocessing._polynomial.PolynomialFeatures'>

P is 
 [[    1.   -10.   100. -1000.]
 [    1.    -8.    64.  -512.]
 [    1.    -3.     9.   -27.]
 [    1.    -1.     1.    -1.]
 [    1.     2.     4.     8.]
 [    1.     8.    64.   512.]]


In [7]:
#Now we can solve for w
w = np.linalg.inv(P.T @ P) @ P.T @ y

print('w is \n', w) 

#(b) Predict y for test point { x = 9 } 
xt = np.array([[9]]).T
testx = polyfn.fit_transform(xt)

ypredicted = testx @ w

print('Predicted y is ',ypredicted)


w is 
 [[ 2.68935636]
 [-0.37722517]
 [ 0.01343815]
 [ 0.00285772]]
Predicted y is  [[2.46609771]]


### Q2(a) - SOLUTION v2 - Solving Step by Step

In [ ]:
### Q2(a) - SOLUTION v2 - Solving Step by Step

x = np.array([[-10, -8, -3, -1,  2,  8]]).T
y = np.array([[5, 5, 4, 3, 2, 2]]).T

P = np.column_stack((np.ones(len(x)),x,x*x,x**3))

w = np.linalg.inv(P.T @ P) @ P.T @ y
print('w is \n', w) 

xt = np.array([[9]]).T

testx = np.column_stack((np.ones(len(xt)),xt,xt*xt,xt**3))

ypredicted = testx @ w
print('Predicted y is ',ypredicted)

### Q2(a) - SOLUTION v3 - using polyfit function within numpy

In [ ]:
### Q2(a) - SOLUTION v3 - using polyfit function within numpy

#Creating x and y arrays
x = np.array([-10, -8, -3, -1,  2,  8])
y = np.array([5, 5, 4, 3, 2, 2])

# polyfit functions calculates the coefficients of the polynomial fit based on least squares
# np.polyfit (x matrix, y matrix, degree of polynomial)
# z contains the coefficients of the polynomial (eg. w values)

z = np.polyfit(x, y, 3) #NOTE that the z values are from highest order to lowest order

print('z is \n', z)

#To find out the predicted value of y for x = 9, you can 
model = np.poly1d(z)    #create a polynomial model using the coefficients in z
ypredicted = model(9)   #call the model and just substitute x=9
print('Predicted y is ',ypredicted)

## Plotting the curve for visualization!

In [ ]:

#--- Plotting---#
plt.plot(x,y,'bo')
xline= np.arange(min(x),max(x),0.1)
yline=model(xline)

plt.plot(xline,yline)
plt.show()


## Q2(c) - Compare this prediction with that of a linear regression

In [ ]:
x = np.array([[-10, -8, -3, -1,  2,  8]]).T
y = np.array([[5, 5, 4, 3, 2, 2]]).T

X = np.column_stack((np.ones((len(x),1)), x))

w = np.linalg.inv(X.T @ X) @ X.T @ y

ylinear = np.array([1 , 9]) @ w

print(ylinear)

In [ ]:
# Other interesting functions

#P = polygen.polyvander(x,3)
#testx = polygen.polyvander(testxvalue,3)
