# EE2211 Tutorial 6

### by Chua Dingjuan (Sept 2022)

## Question 4 Python Codes

In [1]:
import numpy as np
from numpy.linalg import inv 

In [11]:
#Creating x and y arrays
x = np.array([[-1, 0, 0.5, 0.3, 0.8]]).T
y = np.array([[1, 1, -1, 1, -1]]).T

#Padding bias column of ones
X = np.column_stack((np.ones(len(x)),x))

#Solving for w (linear regression)
w = inv(X.T @ X) @ X.T @ y 

print('w is : \n', w)

w is : 
 [[ 0.33333333]
 [-1.11111111]]


In [10]:
#Creating x test matrices
xtest = np.array([[-0.1, 0.4]]).T
Xtest = np.column_stack((np.ones(len(xtest)),xtest))

print('Xtest is : \n', Xtest)

Xtest is : 
 [[ 1.  -0.1]
 [ 1.   0.4]]


In [7]:
#Calculating predictions
y_predict = Xtest @ w

y_predict_class = np.sign(y_predict)

print('Raw predicted y values are :\n', y_predict)
print('Therefore predicted y output class is :\n', y_predict_class)

Raw predicted y values are :
 [[ 0.44444444]
 [-0.11111111]]
Therefore predicted y output class is :
 [[ 1.]
 [-1.]]
