# EE2211 Tutorial 6

### by Chua Dingjuan (Sept 2022)

## Question 5 Python Codes

In [1]:
import numpy as np
from numpy.linalg import inv 

### 5(a) Predict the class label for {𝑥 = −0.1} and {𝑥 = 0.4} based on linear regression towards a one-hot encoded target.

In [6]:
#-- Q5A -- #

x = np.array([[-1, 0, 0.5, 0.3, 0.8]]).T
Y = np.array([[1,0,0], [1,0,0], [0,1,0], [0,0,1], [0,1,0]])

X = np.column_stack((np.ones(len(x)),x))

print('X is : \n', X)

w = inv(X.T @ X) @ X.T @ Y 

print('w is : \n', w)

xtest = np.array([[-0.1, 0.4]]).T
Xtest = np.column_stack((np.ones(len(xtest)),xtest))

y_predict= Xtest @ w

print('y_predict is : \n', y_predict)


X is : 
 [[ 1.  -1. ]
 [ 1.   0. ]
 [ 1.   0.5]
 [ 1.   0.3]
 [ 1.   0.8]]
w is : 
 [[ 0.47798742  0.33333333  0.18867925]
 [-0.64989518  0.55555556  0.09433962]]
y_predict is : 
 [[0.54297694 0.27777778 0.17924528]
 [0.21802935 0.55555556 0.22641509]]


In [7]:
#The following two pieces of codes both returns argmax, but in different formats. 
#Option 1 returns the output directly in one-hot encoding

#Creates an array which returns argmax
y_class_predict = [[1 if y == max(x) else 0 for y in x] for x in y_predict ]
print('y_class_predict is : \n', y_class_predict)

#Option 2 returns the output not in one-hot encoding
#Alternative code below returns the argmax values per row
y_class_predict1 = np.argmax(y_predict,axis=1)
print('y_class_predict1 is : \n', y_class_predict1)


y_class_predict is : 
 [[1, 0, 0], [0, 1, 0]]
y_class_predict1 is : 
 [0 1]


### 5(b) Predict the class label for {𝑥 = −0.1} and { 𝑥 = 0.4} using a polynomial model of 5th order and a one-hot encoded target.

In [8]:
## Polynomial regression
from sklearn.preprocessing import PolynomialFeatures as skpf

x = np.array([[-1, 0, 0.5, 0.3, 0.8]]).T
xtest = np.array([[-0.1, 0.4]]).T

polyfn = skpf(5)
P=polyfn.fit_transform(x)

print('P is : \n', P)

wp = P.T @ inv(P @ P.T) @ Y


print('w is : \n', wp)

P is : 
 [[ 1.      -1.       1.      -1.       1.      -1.     ]
 [ 1.       0.       0.       0.       0.       0.     ]
 [ 1.       0.5      0.25     0.125    0.0625   0.03125]
 [ 1.       0.3      0.09     0.027    0.0081   0.00243]
 [ 1.       0.8      0.64     0.512    0.4096   0.32768]]
w is : 
 [[ 1.00000000e+00  1.77635684e-13 -3.41060513e-13]
 [-5.30313768e+00 -3.70234958e+00  9.00548727e+00]
 [ 5.21976232e+00  1.08728407e+01 -1.60926030e+01]
 [ 6.66624941e+00  9.46978846e+00 -1.61360379e+01]
 [-6.47651463e+00 -1.29098961e+01  1.93864107e+01]
 [-2.61986403e+00 -7.80449422e+00  1.04243583e+01]]


In [9]:
#Creating P matrices for Testing Data
Ptest = polyfn.fit_transform(xtest)

y_predict = Ptest @ wp
print('y_predict is : \n', y_predict)

#The np.argmax function returns the argument for the maximum value (arg of max)
#For the first row of y_predict, the largest value is the first element, index 0
#For the second row of y_predict, the largest value is the theird element, index 2 
#Therefore final value is [0 2]
#In argmax, axis=1 is required so that it returns the arg for each row of y_predict

y_class_predict = np.argmax(y_predict,axis=1)
print('y_class_predict is : \n', y_class_predict)

y_predict is : 
 [[ 1.57522369  0.46828063 -1.04350432]
 [-0.05207932  0.45436978  0.59770954]]
y_class_predict is : 
 [0 2]


In [10]:
#After we find the class of the predicted output, we need to encode it in one-hot format
#This can be done by using sklearn OneHotEncoder function

from sklearn.preprocessing import OneHotEncoder
enc=OneHotEncoder(categories=[[0,1,2]],sparse=False)
tmp = y_class_predict.reshape((len(y_class_predict),1))
enc.fit_transform(tmp)

array([[1., 0., 0.],
       [0., 0., 1.]])