# EE2211 Tutorial 6

### by Chua Dingjuan (Sept 2022)

## Question 6 Python Codes

In [29]:
from sklearn.datasets import load_iris
import numpy as np
from numpy.linalg import inv 
iris_dataset = load_iris()

### 6(a) Split the database into two sets: 74% of samples for training, and 26% of samples for testing. Hint: you might want to utilize from sklearn.model_selection import train_test_split for the splitting.

In [34]:
## (a) split data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
iris_dataset['data'], iris_dataset['target'], test_size=0.26, random_state=0)

print(y_train.shape)
print(y_test.shape)

print('y_test is : \n', y_test)

(111,)
(39,)
y_test is : 
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1 1]


### 6(b) Construct the target output using one-hot encoding.

In [33]:
## (b) one-hot encoding
from sklearn.preprocessing import OneHotEncoder

onehot_encoder=OneHotEncoder(sparse=False)          #sparse=False is used so that we don't have to use .toarray() later
reshaped = y_train.reshape(len(y_train), 1)         #converts y_train into a column vector
Ytr_onehot = onehot_encoder.fit_transform(reshaped) #one-hot encoding!
#print('Ytr_onehot is : \n', Ytr_onehot)

reshaped = y_test.reshape(len(y_test), 1)           #converts y_test into a column vector
Yts_onehot = onehot_encoder.fit_transform(reshaped) #one-hot encoding!
print('Yts_onehot is : \n', Yts_onehot)

Yts_onehot is : 
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


### 6(c) Perform a linear regression for classification (without inclusion of ridge, utilizing one-hot encoding for the learning target) and compute the number of test samples that are classified correctly.

In [36]:
## (c) Linear Classification
w = inv(X_train.T @ X_train) @ X_train.T @ Ytr_onehot
print(w)

yt_est = X_test.dot(w);
yt_cls = [[1 if y == max(x) else 0 for y in x] for x in yt_est ]
print(yt_cls)


[[ 0.11529555  0.20404125 -0.15416052]
 [ 0.21791487 -0.29396894  0.14549901]
 [-0.25363127  0.18246449  0.0362187 ]
 [-0.04023153 -0.58240246  0.57367321]]
[[0, 0, 1], [0, 1, 0], [1, 0, 0], [0, 1, 0], [1, 0, 0], [0, 0, 1], [1, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0], [1, 0, 0], [0, 0, 1], [0, 0, 1], [1, 0, 0], [1, 0, 0], [0, 0, 1], [1, 0, 0], [1, 0, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [0, 0, 1], [0, 0, 1], [1, 0, 0], [0, 0, 1], [0, 0, 1], [0, 0, 1], [1, 0, 0], [0, 0, 1], [0, 0, 1]]


In [38]:
m1 = np.matrix(Yts_onehot)      #np.matrix here is optional
m2 = np.matrix(yt_cls)
difference = np.abs(m1 - m2)

#print(difference)

correct = np.where(~difference.any(axis=1))[0]
accuracy = len(correct)/len(difference)

print(len(correct))
print(accuracy)

28
0.717948717948718


In [43]:
## (d) Polynomial Classification
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(2)
P = poly.fit_transform(X_train)
Pt = poly.fit_transform(X_test)
if P.shape[0] > P.shape[1]:
 wp = inv(P.T @ P) @ P.T @ Ytr_onehot
else:
 wp = P.T @ inv(P @ P.T) @ Ytr_onehot
#print(wp)

yt_est_p = Pt.dot(wp);
yt_cls_p = [[1 if y == max(x) else 0 for y in x] for x in yt_est_p ]
#print(yt_cls_p)

m1 = np.matrix(Yts_onehot)
m2 = np.matrix(yt_cls_p)
difference = np.abs(m1 - m2)
#print(difference)

correct_p = np.where(~difference.any(axis=1))[0]
accuracy_p = len(correct_p)/len(difference)
print(len(correct_p))
print(accuracy_p) 

38
0.9743589743589743
